- name: rabbit-pb
  gather_facts: no
  hosts: servers
  tasks:
    - apt:
        pkg:
          - gnupg
          - apt-transport-https
        state: latest
        update_cache: true
    - apt_key:
        url: https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
        keyring: /usr/share/keyrings/com.rabbitmq.team.gpg
    - apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
        keyring: /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg
    - apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
        keyring: /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg
    - apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/debian buster main"
        state: present
    - apt_repository:
        repo: "deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/debian buster main"
        state: present
    - apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.novemberain.com/rabbitmq/rabbitmq-erlang/deb/debian buster main"
        state: present
    - apt_repository:
        repo: "deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.novemberain.com/rabbitmq/rabbitmq-erlang/deb/debian buster main"
        state: present
    - apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/debian buster main"
        state: present
    - apt_repository:
        repo: "deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/debian buster main"
        state: present
    - apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.novemberain.com/rabbitmq/rabbitmq-server/deb/debian buster main"
        state: present
    - apt_repository:
        repo: "deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.novemberain.com/rabbitmq/rabbitmq-server/deb/debian buster main"
        state: present
    - apt:
        pkg:
          - erlang-base
          - erlang-asn1
          - erlang-crypto
          - erlang-eldap
          - erlang-ftp
          - erlang-inets
          - erlang-mnesia
          - erlang-os-mon
          - erlang-parsetools
          - erlang-public-key
          - erlang-runtime-tools
          - erlang-snmp
          - erlang-ssl
          - erlang-syntax-tools
          - erlang-tftp
          - erlang-tools
          - erlang-xmerl
        state: latest
        update_cache: true
    - apt:
        name: rabbitmq-server
        state: fixed
    - rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
    - rabbitmq_user:
        user: user
        password: password
        vhost: /
        tags: administrator
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
    - service:
        name: rabbitmq-server
        state: restarted
    - shell: echo YLXWSHZFLHEKPYCRHUGK > /var/lib/rabbitmq/.erlang.cookie
    - shell: rabbitmqctl stop_app
    - shell: rabbitmqctl join_cluster rabbit@debian4
    - shell: rabbitmqctl start_app
    - shell: rabbitmqctl set_policy ha-all "" '{"ha-mode":"all","ha-sync-mode":"automatic"}'
